- hosts: workshop_hosts
  become: true
  vars_files:
    - group_vars/qiime_hosts.yml
    - group_vars/VAULT
  pre_tasks:
    - name: Attach volume to instance
      include_role:
        name: attached-volumes
    - name: create home dir on /mnt
      file:
        path: /mnt/home
        state: directory
        mode: 0755
  roles:
    - common
    - geerlingguy.pip
    - uchida.miniconda
    - slg.users
  post_tasks:
    - name: Move /tmp to vdc
      block:
        - name: Create worker tmpdir on vdc
          file:
            path: /mnt/tmpdisk
            state: directory
            owner: root
            group: root
            mode: '1777'
        - name: stat links
          stat:
            path: /tmp
          register: links
        - name: remove old tmp
          file:
            path: /tmp
            state: absent
          when: links.stat.islnk is defined and not links.stat.islnk
        - name: Link /tmp to /mnt/tmpdisk
          file:
            src: /mnt/tmpdisk
            dest: /tmp
            state: link
          become: yes
          become_user: root
          when: links.stat.islnk is defined and not links.stat.islnk
      when: attached_volumes is defined
      